version: "3.8"

services:
  database:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: node:latest
    container_name: backend_container
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - database

  frontend:
    image: node:latest
    container_name: frontend_container
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - backend

volumes:
  mysql_data:
